name: PNPM Config Dependency Action
description: Updates pnpm config dependencies and regular dependencies, creating PRs with changesets
branding:
  icon: package
  color: yellow
inputs:
  app-id:
    description: GitHub App ID for authentication
    required: true
  app-private-key:
    description: GitHub App private key (PEM format)
    required: true
  branch:
    description: Branch name for dependency update PR
    required: false
    default: pnpm/config-deps
  config-dependencies:
    description: |
      Config dependencies to update (one per line, exact match).
      Example:
        @savvy-web/pnpm-plugin-silk
        typescript
    required: false
    default: ""
  dependencies:
    description: |
      Regular dependencies to update (one per line, supports globs).
      Example:
        effect
        @effect/*
        @savvy-web/*
    required: false
    default: ""
  skip-token-revoke:
    description: Skip revoking the GitHub App token on cleanup
    required: false
    default: "false"
  dry-run:
    description: Run without making changes (for testing)
    required: false
    default: "false"
  log-level:
    description: |
      Logging verbosity level.
      - info: Standard logging (default)
      - debug: Verbose logging with detailed state information
    required: false
    default: info
  run:
    description: |
      Commands to run after dependency updates (one per line).
      Useful for running linting, tests, or build commands after updates.
      Example:
        pnpm lint:fix
        pnpm test
    required: false
    default: ""
outputs:
  token:
    description: Generated GitHub App installation token
  pr-number:
    description: Pull request number (if created or updated)
  pr-url:
    description: Pull request URL (if created or updated)
  updates-count:
    description: Number of dependencies updated
  has-changes:
    description: Whether any dependencies were updated
runs:
  using: node24
  pre: dist/pre.js
  main: dist/main.js
  post: dist/post.js
